### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stevenlin-TW**
Name: 林琮訓 (same with discord username)
API:
http://18.177.218.111:3000/api/attractions?page=1
http://18.177.218.111:3000/api/attractions?page=0&keyword=藝文館所
http://18.177.218.111:3000/api/attractions?page=0&keyword=北
http://18.177.218.111:3000/api/attraction/10
http://18.177.218.111:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues listed below:

1. Response format of http://18.177.218.111:3000/api/attraction/10 is incorrect.
2. `nextPage` field of http://18.177.218.111:3000/api/attractions?page=1&keyword=%E5%8C%97 should be null, because it's the last page of keyword filtered data.
3. Try to use `GROUP_CONCAT` and `JOIN` to get attraction data and image urls all at once, much better than get image urls one by one.

Re-request review after you fix them.

**Comment by stevenlin-TW** [comment]
Hi Teacher,
I've done modifying my code, please take a look, thank u!

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by stevenlin-TW** [comment]
Sorry I thought I had set it, now I think I have actually done it.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your APIs are down after first 1 testing.

**Comment by stevenlin-TW** [comment]
I made some mistake...
this time I think it'd be fine!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
