### PR TITLE
Dec 4 02:35

### PR DESCRIPTION
**Pull request by stevenlin-TW**
林琮訓
http://18.177.218.111:3000/
http://18.177.218.111:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but padding of date input should not be 0.

**Comment by stevenlin-TW** [comment]
林琮訓
http://18.177.218.111:3000/
http://18.177.218.111:3000/attraction/10

I've made modification for the padding of input date, please check for me, thank you.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Comment by stevenlin-TW** [comment]
Done setting teacher as reviewer.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
